.github/workflows/dev.yaml

Reverts zeplin/microsoft-teams-app#127

Revert "[MTA-98] Remove creating redundant s3 files"

---

src/server/services/configurationService/configurationService.ts
src/server/services/workspaceService/workspaceService.ts

Fix types of sdk functions' arguments

---

src/server/services/authService/authService.ts

Fix setting custom Zeplin url

---

.github/workflows/code_quality.yaml
.github/workflows/daily.yaml
package.json

Add a daily job to fix npm audit issues.

Daily CI job

---

.github/pull_request_template.md
.github/workflows/code_quality.yaml
.github/workflows/daily.yaml
.github/workflows/dev.yaml
.github/workflows/production.yaml

Trigger `Release Dev` after `Check Code Quality` is finished.

ci: trigger release dev after code quality check

---

src/server/adapters/messageQueue/messageQueue.ts

fix: Fix removing completed jobs from Redis

---

src/server/queueListener.ts
src/server/router/webhookEventRouter/webhookEventRouter.ts
src/server/services/webhookEventService/webhookEventService.ts

refactor: Add more logs to track webhook events

---

.env.example
CONTRIBUTING.md

chore: Fix typos in contributing.md and .env.example

---

package-lock.json

fix: fix critical/high vulnerabilities

---

src/server/adapters/redis/redis.ts

fix: Handle redis connect and error events

---

package-lock.json
src/server/adapters/logger/logProvider.ts

fix: Correct log time format

---

package-lock.json
package.json
src/server/adapters/adapters.ts
src/server/adapters/logger/logProvider.ts
src/server/adapters/logger/logger.ts
src/server/config.ts

fix: Remove logdna loggers

---

package-lock.json

chore: update vulnerable packages

---

package-lock.json

Fix critical npm audit issues.
`found 0 vulnerabilities`
> N/A

fix: npm audit issues

---

package-lock.json
package.json
src/server/app.ts
src/server/types/helmet.d.ts

- Add helmet
- Remove `x-powered-by` header

fix: add helmet and remove `x-powered-by` header

---

package-lock.json
package.json

bump mongoose to latest and remove `^`.

chore: bump mongoose

---

src/server/adapters/requester/requester.ts

fix: axios type error

---

Dockerfile

build: fix dockerfile

---

pm2.json
src/server/adapters/messageQueue/messageQueue.ts
src/server/adapters/mongo/mongo.ts
src/server/app.ts

feat: send worker logs to stdout and add init logging

---

src/server/app.ts

fix: remove queuelistener await

---

src/client/containers/LoginContainer/LoginContainer.tsx
src/client/containers/LoginContainer/hooks/useLogin.ts
src/client/containers/ZeplinAuthEndContainer/ZeplinAuthEndContainer.tsx

fix: pass auth code to login container

---

src/client/containers/ConfigurationUpdateContainer/components/ConfigurationUpdate.tsx

Fix typo on configuration update page
> Fix [#1]()

fix: Fix typo on configuration update page
